#!/usr/bin/env node
// Regenerates src/cards.js from the official Arcs card library at https://cards.buriedgiant.com.
//
// Draft links store cards by their position in LEADERS and LORE, so this script refuses to
// reorder or drop existing cards: new cards may only be appended.

import { writeFile } from 'node:fs/promises';

const LIBRARY = 'https://cardcdn.buriedgiant.com';
const OUTPUT = new URL('../src/cards.js', import.meta.url);
const SETS = { arcsbasegame: 'base', 'leaders-lore': 'pack' };

// Published errata that change card text, applied as exact replacements.
const TEXT_ERRATA = {
  Upstart: [
    '*Callow*. You can only **tax** Loyal cities if you control them.',
    '*Callow*. You cannot **tax** cities that you do not control.',
  ],
  Agitator: [
    'If a Rival attacks you in **battle** and rolls {intercept},',
    'If a Rival attacks you in **battle** and is intercepted,',
  ],
  'Living Structures': [
    'Replace a Loyal starport with a Loyal city or vice versa.',
    'Replace a Loyal starport in a slot with a Loyal city or vice versa.',
  ],
};

// Errata entries already checked and needing no text change (the library text is current).
const REVIEWED_ERRATA = new Set(["Empath's Bond", 'Force Beams']);

async function fetchJSON(path) {
  const response = await fetch(`${LIBRARY}/${path}`);
  if (!response.ok) throw new Error(`GET ${path}: ${response.status}`);
  return response.json();
}

// The library ships cards in compress-json format. Only strings, arrays, objects and booleans
// matter for the fields read here.
function decompress([values, rootKey]) {
  const base62 = key => [...key].reduce((n, ch) => n * 62 + '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz'.indexOf(ch), 0);
  const cache = new Map();
  const ref = key => {
    if (!cache.has(key)) cache.set(key, decode(values[base62(key)]));
    return cache.get(key);
  };
  const decode = value => {
    if (typeof value !== 'string' || value[1] !== '|') return value;
    const body = value.slice(2);
    switch (value[0]) {
      case 'o': {
        const [keysRef, ...valueRefs] = body.split('|');
        const keys = [ref(keysRef)].flat();
        return Object.fromEntries(keys.map((key, i) => [key, ref(valueRefs[i])]));
      }
      case 'a': return body === '' ? [] : body.split('|').map(ref);
      case 'b': return body === 'T';
      case 's': return body;
      default: return value;
    }
  };
  return ref(rootKey);
}

function cleanText(text) {
  return text
    .replace(/ /g, ' ')
    .replace(/`symbol:(\w+)`/g, '{$1}')
    .replace(/\$link:([^$]+)\$/g, '$1');
}

function applyErrata(card) {
  const erratum = TEXT_ERRATA[card.name];
  if (!erratum) return card;
  const [before, after] = erratum;
  if (!card.text.includes(before)) throw new Error(`Erratum for ${card.name} no longer matches the library text`);
  return { ...card, text: card.text.replace(before, after) };
}

function toCards(all, tag, idPattern) {
  return all
    .filter(card => card.game === 'arcs' && card.locale === 'en-US' && SETS[card.product] && card.tags.includes(tag))
    .map(card => ({
      number: Number(idPattern.exec(card.id)[1]),
      set: SETS[card.product],
      name: card.name,
      text: cleanText(card.text),
    }))
    .sort((a, b) => a.number - b.number)
    .map(applyErrata);
}

async function assertAppendOnly(kind, next) {
  let current;
  try {
    current = (await import(OUTPUT.href))[kind];
  } catch {
    return;
  }
  current.forEach((card, i) => {
    if (next[i]?.name !== card.name) {
      throw new Error(`${kind}[${i}] would change from ${card.name} to ${next[i]?.name ?? 'nothing'}; existing links would break`);
    }
  });
}

function checkErrata(errata, names) {
  const unreviewed = (errata.arcs?.['en-US'] ?? [])
    .map(entry => entry.card)
    .filter(name => names.has(name) && !TEXT_ERRATA[name] && !REVIEWED_ERRATA.has(name));
  for (const name of unreviewed) console.warn(`warning: unreviewed erratum for ${name} — check ${LIBRARY}/errata.json`);
}

const literal = cards => cards
  .map(card => `  { number: ${card.number}, set: '${card.set}', name: ${JSON.stringify(card.name)},\n    text: ${JSON.stringify(card.text)} },`)
  .join('\n');

const all = decompress(await fetchJSON('cards.min.json'));
const LEADERS = toCards(all, 'Leader', /LEAD(\d+)$/);
const LORE = toCards(all, 'Lore', /-L(\d+)$/);

await assertAppendOnly('LEADERS', LEADERS);
await assertAppendOnly('LORE', LORE);
checkErrata(await fetchJSON('errata.json'), new Set([...LEADERS, ...LORE].map(card => card.name)));

await writeFile(OUTPUT, `// Generated by scripts/sync-cards.mjs from the official card library. Do not edit by hand.
// Draft links refer to cards by position in these lists, so cards may only ever be appended.

export const LEADERS = [
${literal(LEADERS)}
];

export const LORE = [
${literal(LORE)}
];
`);

console.log(`Wrote ${LEADERS.length} leaders and ${LORE.length} lore cards to src/cards.js`);
